### ISSUE TITLE
Planning to support future releases of good?

### ISSUE THREAD

**Issue by StarpTech** [lancespeelmon/good-winston#1]
Hi
at first thanks for this great plugin. Do you plan to support the reporter interface instead to use the no longer maintained `good-reporter` module? I will try to submit a pull request in the near future. thanks.

**Comment by lancespeelmon** [comment]
@StarpTech thanks! I was not aware of the `good-reporter` deprecation. A PR would be fantastic if you have time. :smile: Thanks, L

**Comment by lancespeelmon** [comment]
IIUC, most of this change was made in this commit: https://github.com/lancespeelmon/good-winston/commit/8fd115e6a082de4b5652670e27e691650cd0c831
But maybe you know something I don't... :smile_cat:
