### ISSUE TITLE
Support winston's meta-info logging

### ISSUE THREAD

**Issue by devinivy** [lancespeelmon/good-winston#2]
Just a request!  Support winston's meta-info parameter (e.g. `winston.info(message, meta)`) by accepting log data of the format,
```json5
{
  message: 'Something happened!',
  meta: {/* ... */}
}
```

If you desire this functionality, I could probably whip-up a PR.

**Comment by lancespeelmon** [comment]
@devinivy That would be great... I have jumped ship to bunyan, so my ability to affect change here is low... but I will review the PR to keep things going... Thanks, L

**Comment by devinivy** [comment]
Alright– cool.  If you haven't heard from me within a week or two, no need to leave this request hanging around.  I do plan to make the change, though!

**Comment by lancespeelmon** [comment]
@devinivy We recently had a fairly big change to the code base from another contributor. Your PR may be worth reconsidering given the refreshed code base. :) Best, L
